version: '3.8'

services:
  web-interface:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_PORT=3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api-server
    networks:
      - nikcli-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-server:
    image: nikcli-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - nikcli-network
    restart: unless-stopped

networks:
  nikcli-network:
    driver: bridge

volumes:
  data:
  logs: